# site settings
title: sikusiku
subtitle: by HTML5 UP
email: sikuism@gmail.com
description: Full stack developer wannabe!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: JINOOK HONG
street_address:
city: Seoul
state: 
zip_code: 
country: Repulic of Korea
phone: (716) 555-5555

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url: https://github.com/sikusiku
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
